import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
import simpleImportSort from 'eslint-plugin-simple-import-sort'

export default {
  languageOptions: {
    // ecmaVersion: 2022,
  },
  plugins: {
    '@stylistic': stylistic,
    'simple-import-sort': simpleImportSort,
  },
  rules: {
    ...js.configs.recommended.rules,
    'accessor-pairs': 'warn',
    'array-callback-return': 'error',
    'arrow-body-style': 'off',
    'block-scoped-var': 'error',
    camelcase: ['error', {allow: ['^_*unstable_', '^UNSAFE_']}],
    'capitalized-comments': 'off',
    'class-methods-use-this': 'warn',
    complexity: ['warn', 30],
    'consistent-return': 'error',
    'consistent-this': ['error', 'self'],
    'constructor-super': 'error',
    curly: 'error',
    'default-case': 'error',
    'dot-notation': ['error', {allowKeywords: true}],
    eqeqeq: 'off',
    'for-direction': 'error',
    'func-name-matching': 'error',
    'func-names': 'off',
    'func-style': 'off',
    'getter-return': ['error', {allowImplicit: true}],
    'guard-for-in': 'error',
    'id-length': 'off', // catch undescriptive names in code review
    'id-match': 'off',
    'init-declarations': 'off',
    'max-depth': ['error', 4],
    'max-lines': 'off',
    'max-nested-callbacks': ['error', 3],
    'max-params': ['error', 5],
    'max-statements': ['warn', 50],
    'new-cap': ['error', {capIsNew: false}],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-await-in-loop': 'off', // should be caught in code reviews on dangerous usage
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'except-parens'],
    'no-console': ['error', {allow: ['warn', 'error']}],
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-continue': 'off',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'off', // turned off in favor of import/no-duplicates
    'no-else-return': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-function': 'warn',
    'no-empty-pattern': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': 'off',
    'no-implicit-globals': 'off',
    'no-implied-eval': 'error',
    'no-inline-comments': 'off',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'off',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'warn',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'off',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'warn',
    'no-plusplus': 'off',
    'no-proto': 'error',
    'no-prototype-builtins': 'off',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-restricted-globals': ['error', 'event'],
    'no-restricted-imports': ['error', 'underscore', 'jquery'],
    'no-restricted-properties': 'off',
    'no-restricted-syntax': ['error', 'WithStatement'],
    'no-return-assign': 'error',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-ternary': 'off',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'off',
    'no-underscore-dangle': 'off',
    'no-unexpected-multiline': 'warn',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-unused-vars': ['error', {args: 'none', vars: 'all', ignoreRestSiblings: true}],
    'no-use-before-define': ['error', 'nofunc'],
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': ['warn', {location: 'anywhere', terms: ['todo', 'fixme', 'xxx']}],
    'no-with': 'error',
    'object-shorthand': ['error', 'methods'],
    'one-var': ['error', 'never'],
    'operator-assignment': ['error', 'always'],
    'prefer-arrow-callback': ['warn', {allowNamedFunctions: true}],
    'prefer-destructuring': 'off',
    'prefer-numeric-literals': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'require-yield': 'error',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'sort-vars': 'off',
    strict: ['error', 'never'],
    'symbol-description': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    // "stylistic" rules (previously in eslint core)
    '@stylistic/array-bracket-newline': ['error', {multiline: true}],
    '@stylistic/array-bracket-spacing': ['error', 'never'],
    '@stylistic/array-element-newline': 'off',
    '@stylistic/arrow-parens': ['error', 'always'],
    '@stylistic/arrow-spacing': 'error',
    '@stylistic/block-spacing': ['error', 'always'],
    '@stylistic/brace-style': ['error', '1tbs', {allowSingleLine: false}],
    '@stylistic/comma-dangle': 'off',
    '@stylistic/comma-spacing': ['error', {after: true, before: false}],
    '@stylistic/comma-style': ['error', 'last'],
    '@stylistic/computed-property-spacing': 'error',
    '@stylistic/dot-location': ['error', 'property'],
    '@stylistic/eol-last': 'error',
    '@stylistic/func-call-spacing': 'error',
    '@stylistic/function-paren-newline': ['error', 'consistent'],
    '@stylistic/generator-star-spacing': ['error', {after: true, before: false}],
    '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
    '@stylistic/indent': ['error', 2, {SwitchCase: 1}],
    '@stylistic/jsx-quotes': ['error', 'prefer-double'],
    '@stylistic/key-spacing': ['error', {afterColon: true, beforeColon: false}],
    '@stylistic/keyword-spacing': 'error',
    '@stylistic/line-comment-position': 'off',
    '@stylistic/linebreak-style': 'error',
    '@stylistic/lines-around-comment': 'off',
    '@stylistic/lines-between-class-members': 'off', // turn on if supports methods only
    '@stylistic/max-len': ['error', 100, 2],
    '@stylistic/max-statements-per-line': ['error', {max: 1}],
    '@stylistic/multiline-comment-style': 'off',
    '@stylistic/multiline-ternary': 'off',
    '@stylistic/new-parens': 'off',
    '@stylistic/newline-per-chained-call': ['error', {ignoreChainWithDepth: 3}],
    '@stylistic/no-confusing-arrow': ['error', {allowParens: true}],
    '@stylistic/no-extra-parens': ['error', 'functions'],
    '@stylistic/no-extra-semi': 'error',
    '@stylistic/no-floating-decimal': 'error',
    '@stylistic/no-mixed-operators': 'error',
    '@stylistic/no-mixed-spaces-and-tabs': 'error',
    '@stylistic/no-multi-spaces': 'error',
    '@stylistic/no-multiple-empty-lines': ['error', {max: 2}],
    '@stylistic/no-tabs': 'error',
    '@stylistic/no-trailing-spaces': 'error',
    '@stylistic/no-whitespace-before-property': 'error',
    '@stylistic/nonblock-statement-body-position': 'off',
    '@stylistic/object-curly-newline': 'off',
    '@stylistic/object-curly-spacing': ['error', 'never'],
    '@stylistic/object-property-newline': 'off',
    '@stylistic/one-var-declaration-per-line': 'off',
    '@stylistic/operator-linebreak': 'off', // conflicts with prettier
    '@stylistic/padded-blocks': 'off',
    '@stylistic/padding-line-between-statements': 'off',
    '@stylistic/quote-props': ['error', 'as-needed'],
    '@stylistic/quotes': ['error', 'single', 'avoid-escape'],
    '@stylistic/rest-spread-spacing': ['error', 'never'],
    '@stylistic/semi-spacing': ['error', {after: true, before: false}],
    '@stylistic/semi-style': 'off',
    '@stylistic/semi': ['error', 'never'],
    '@stylistic/space-before-blocks': 'error',
    '@stylistic/space-before-function-paren': ['error', {anonymous: 'always', named: 'never'}],
    '@stylistic/space-in-parens': ['error', 'never'],
    '@stylistic/space-infix-ops': 'error',
    '@stylistic/space-unary-ops': 'error',
    '@stylistic/spaced-comment': 'off',
    '@stylistic/switch-colon-spacing': 'error',
    // simple import plugin
    'simple-import-sort/imports': 'warn',
    'simple-import-sort/exports': 'warn',
  },
}

